# Generated by Django 4.0.3 on 2022-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Idade', models.IntegerField()),
                ('Selecao', models.CharField(max_length=150)),
            ],
        ),
    ]
