# Generated by Django 4.0.3 on 2022-04-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Cpf', models.IntegerField()),
                ('DataNascimento', models.IntegerField()),
            ],
        ),
    ]
